### ISSUE TITLE
Typo at Demo Scene

### ISSUE THREAD

**Issue by joao-pedro-braz** [mechPenSketch/FiniteStateMachine#2]
## Hello There!

I've spotted a small typo on the naming of one of the sprites in the Demo Scene.
![image](https://user-images.githubusercontent.com/37230465/92545143-e18c4700-f225-11ea-9f51-42c7fced0be7.png)
> It should be "Stopwatch", but instead it's "Stropwatch"

Thank you for your Plugin, I really appreciate your effort.

**Comment by mechPenSketch** [comment]
You're welcome. And thanks for letting me know; the misspelling should be fixed by now.
